// 手写实现InstanceOf
// 手写compose和pipe
// 手写new操作符
// 柯里化与反柯里化
// 实现符合A+规范的Promise
// 用generator模拟async-await
// 手写Promise.all和allSettled
// 手写Promise.race和Promise.any
// 给Promise增加超时功能
// 实现一个并发控制调度器
// 实现请求重试
